### ISSUE TITLE
Tried npm then yarn inst

### ISSUE THREAD

**Issue by ludo1960** [toadkicker/nuxt-crud-example#2]
Not working, npm stalls at non bootsrapped login page, yarn results in "page not working"

**Comment by toadkicker** [comment]
Use yarn

**Comment by ludo1960** [comment]
Read my post again, tried yarn too!

Sent from my iPhone

On 5 Aug 2019, at 16:17, Todd Baur <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/toadkicker/nuxt-crud-example/issues/2>.

**Comment by toadkicker** [comment]
Package is updated w/ latest versions and should fix the issues.

**Comment by ludo1960** [comment]
All works fine now (I used npm) thanks for sorting it. Tutorial looks prety cool, Thanks again nice job!

**Comment by ludo1960** [comment]
Spoke to soon, cant login with tom@example.com and test123

**Comment by toadkicker** [comment]
It's controlled by `./users.json` and the password is `test1234`

**Comment by ludo1960** [comment]
Thanks

Sent from my iPhone

On 6 Aug 2019, at 15:10, Todd Baur <notifications@github.com<mailto:notifications@github.com>> wrote:


It's controlled by ./users.json and the password is test1234
